# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=17, unique=True, verbose_name='Номер счета')),
                ('description', models.CharField(max_length=256, verbose_name='Назначение платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Сумма платежа, заказанная продавцом')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта платежа, заказанная продавцом')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Сумма платежа в валюте, в которой покупатель производит платеж')),
                ('paid_currency', models.CharField(max_length=3, verbose_name='Валюта, в которой производится платеж')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Идентификатор платежной системы, выбранной покупателем')),
                ('payment_system', models.CharField(max_length=50, verbose_name='Идентификатор платежного метода')),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер платежа в системе PayMaster')),
                ('payer_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор плательщика в платежной системе')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата платежа')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('edition_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name_plural': 'Счета',
                'verbose_name': 'Счет',
            },
        ),
    ]
